### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by domhnallmorr** [AndreaSillano/VidDownloader#1]
Nice app, just tried it out and seems to be working well. Thought I would provide some observations;

Without ffmpeg installed a fairly cryptic error is generated. The app also freezes requiring a restart to  download another video. Would be nice if that was better handled;

```
Converting to MP3...
It may take a while...
Error: [WinError 193] %1 is not a valid Win32 application
```

Getting several image warning, presumably from the inclusion of the video thumbnail, doesn't effect functionality though

```
warnings.warn(f"{type(self).__name__} Warning: Given image is not CTkImage but {type(image)}. Image can not be scaled on HighDPI displays, use CTkImage instead.\n")
```

Would be nice if it used something like poetry for handling dependencies.

Hope this helps, thanks!

**Comment by AndreaSillano** [comment]
Thank you for your observations, I'm going to fix those issues in the next days

**Comment by AndreaSillano** [comment]
Fixed!
